// <auto-generated />
namespace Technines_irangos_rezervacij.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddEquipment : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddEquipment));
        
        string IMigrationMetadata.Id
        {
            get { return "201804231013358_AddEquipment"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
